/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modul7_2;

import javax.swing.JOptionPane;

/**
 *
 * @author A455L
 */
public class Frame1 extends javax.swing.JFrame {

    /**
     * Creates new form Frame1
     */
    public Frame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jarijari = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        volume1 = new javax.swing.JButton();
        cobalagi2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pjg = new javax.swing.JTextField();
        lebar = new javax.swing.JTextField();
        tinggi = new javax.swing.JTextField();
        hitung = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cobalagi = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        hitung1 = new javax.swing.JButton();
        sisi = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cobalagi1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTabbedPane1.setBackground(new java.awt.Color(255, 153, 204));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jPanel3.setBackground(new java.awt.Color(255, 153, 153));
        jPanel3.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Trajan Pro", 0, 14)); // NOI18N
        jLabel8.setText("Jari-jari :");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(30, 50, 70, 14);
        jPanel3.add(jarijari);
        jarijari.setBounds(110, 40, 170, 30);

        jLabel9.setFont(new java.awt.Font("Trajan Pro", 0, 12)); // NOI18N
        jLabel9.setText("cm");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(300, 40, 30, 30);

        volume1.setText("Volume");
        volume1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        volume1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volume1ActionPerformed(evt);
            }
        });
        jPanel3.add(volume1);
        volume1.setBounds(70, 150, 210, 30);

        cobalagi2.setText("Coba Lagi");
        cobalagi2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cobalagi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cobalagi2ActionPerformed(evt);
            }
        });
        jPanel3.add(cobalagi2);
        cobalagi2.setBounds(70, 200, 210, 30);

        jTabbedPane1.addTab("BOLA", jPanel3);

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Trajan Pro", 0, 14)); // NOI18N
        jLabel2.setText(" Panjang :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 30, 90, 15);

        jLabel3.setFont(new java.awt.Font("Trajan Pro", 0, 14)); // NOI18N
        jLabel3.setText("Lebar :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 70, 70, 15);

        jLabel4.setFont(new java.awt.Font("Trajan Pro", 0, 14)); // NOI18N
        jLabel4.setText("Tinggi :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 110, 70, 15);
        jPanel1.add(pjg);
        pjg.setBounds(110, 20, 150, 30);
        jPanel1.add(lebar);
        lebar.setBounds(110, 60, 150, 30);
        jPanel1.add(tinggi);
        tinggi.setBounds(110, 100, 150, 30);

        hitung.setText("Hitung");
        hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungActionPerformed(evt);
            }
        });
        jPanel1.add(hitung);
        hitung.setBounds(70, 160, 210, 30);

        jLabel11.setFont(new java.awt.Font("Trajan Pro", 0, 12)); // NOI18N
        jLabel11.setText("cm");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(280, 100, 30, 30);

        jLabel12.setFont(new java.awt.Font("Trajan Pro", 0, 12)); // NOI18N
        jLabel12.setText("cm");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(280, 60, 30, 30);

        jLabel14.setFont(new java.awt.Font("Trajan Pro", 0, 12)); // NOI18N
        jLabel14.setText("cm");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(280, 20, 30, 30);

        cobalagi.setText("Coba Lagi");
        cobalagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cobalagiActionPerformed(evt);
            }
        });
        jPanel1.add(cobalagi);
        cobalagi.setBounds(70, 203, 210, 30);

        jTabbedPane1.addTab("BALOK", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));
        jPanel2.setLayout(null);

        hitung1.setText("Hitung");
        hitung1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitung1ActionPerformed(evt);
            }
        });
        jPanel2.add(hitung1);
        hitung1.setBounds(80, 160, 210, 30);
        jPanel2.add(sisi);
        sisi.setBounds(120, 50, 150, 30);

        jLabel15.setFont(new java.awt.Font("Trajan Pro", 0, 14)); // NOI18N
        jLabel15.setText("Sisi :");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(60, 60, 70, 14);

        jLabel16.setFont(new java.awt.Font("Trajan Pro", 0, 12)); // NOI18N
        jLabel16.setText("cm");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(280, 50, 30, 30);

        cobalagi1.setText("Coba Lagi");
        cobalagi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cobalagi1ActionPerformed(evt);
            }
        });
        jPanel2.add(cobalagi1);
        cobalagi1.setBounds(80, 210, 210, 30);

        jTabbedPane1.addTab("KUBUS", jPanel2);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 60, 490, 300);

        jPanel4.setBackground(new java.awt.Color(255, 204, 204));
        jPanel4.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tekton Pro Cond", 1, 18)); // NOI18N
        jLabel1.setText("PROGRAM PENGHITUNG VOLUME BANGUN RUANG");
        jPanel4.add(jLabel1);
        jLabel1.setBounds(40, 10, 710, 40);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 0, 480, 360);

        setBounds(0, 0, 387, 401);
    }// </editor-fold>//GEN-END:initComponents

    private void hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungActionPerformed
        int Panjang, Lebar, Tinggi;
        Panjang = Integer.parseInt(pjg.getText());
        Lebar = Integer.parseInt(lebar.getText());
        Tinggi = Integer.parseInt(tinggi.getText());
        
        int hasil = Panjang*Lebar*Tinggi;
        try{
            JOptionPane.showMessageDialog(null, "Volume Balok adalah :"+hasil, "Volume", 
                    JOptionPane.INFORMATION_MESSAGE);
            
        }catch (Exception e){
              JOptionPane.showMessageDialog(null, "Error :"+e, "Gagal", 
                    JOptionPane.WARNING_MESSAGE);
        }




        // TODO add your handling code here:
    }//GEN-LAST:event_hitungActionPerformed

    private void hitung1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitung1ActionPerformed
        int Sisi;
        Sisi = Integer.parseInt(sisi.getText());
        
        int hasil = Sisi*Sisi*Sisi;
           try{
            JOptionPane.showMessageDialog(null, "Luas permukaan kubus adalah :"+hasil, "Luas Permukaan", 
                    JOptionPane.INFORMATION_MESSAGE);
            
        }catch (Exception e){
              JOptionPane.showMessageDialog(null, "Error :"+e, "Gagal", 
                    JOptionPane.WARNING_MESSAGE);
        }

        










        // TODO add your handling code here:
    }//GEN-LAST:event_hitung1ActionPerformed

    private void volume1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volume1ActionPerformed
    float Jari;
        Jari = Integer.parseInt(jarijari.getText());
        
        float hasil = (float) (4/3*Math.PI*Jari*Jari*Jari);
           try{
            JOptionPane.showMessageDialog(null, "Volume Bola adalah :"+hasil, "Volume", 
                    JOptionPane.INFORMATION_MESSAGE);
            
        }catch (Exception e){
              JOptionPane.showMessageDialog(null, "Error :"+e, "Gagal", 
                    JOptionPane.WARNING_MESSAGE);
        }




        // TODO add your handling code here:
    }//GEN-LAST:event_volume1ActionPerformed

    private void cobalagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cobalagiActionPerformed
        pjg.setText("");
        lebar.setText("");
        tinggi.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_cobalagiActionPerformed

    private void cobalagi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cobalagi1ActionPerformed
       sisi.setText("");
       
// TODO add your handling code here:
    }//GEN-LAST:event_cobalagi1ActionPerformed

    private void cobalagi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cobalagi2ActionPerformed
    jarijari.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_cobalagi2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cobalagi;
    private javax.swing.JButton cobalagi1;
    private javax.swing.JButton cobalagi2;
    private javax.swing.JButton hitung;
    private javax.swing.JButton hitung1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jarijari;
    private javax.swing.JTextField lebar;
    private javax.swing.JTextField pjg;
    private javax.swing.JTextField sisi;
    private javax.swing.JTextField tinggi;
    private javax.swing.JButton volume1;
    // End of variables declaration//GEN-END:variables
}
